name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.12

      - run: cd docs && bun install --frozen-lockfile
      - run: cd docs && bun run build
      - run: cd packages/another-react-router && bun install --frozen-lockfile
      - run: cd packages/another-react-router && bun run build
